sudo: required
services:
    - docker
before_install:
    - docker build -t jomonjames/docker_react -f Dockerfile.dev .
script:
    - docker run -e CI=true jomonjames/docker_react npm run test

deploy:
    provider: elasticbeanstalk
    region: "us-east-1"
    app: "docker99"
    env: "Docker99-env"
    bucket_name: "elasticbeanstalk-us-east-1-891377336193"
    bucket_path: "docker99"
    on:
      branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: "$AWS_SERECT_KEY"
