sudo: required
services:
    - docker
before_install:
    - docker build -t jomonjames/docker_react .
deploy:
    provider: elasticbeanstalk
    region: "us-east-1"
    app: "docker"
    env: "Docker-env-2"
    bucket_name: "elasticbeanstalk-us-east-1-471112538347"
    bucket_path: "docker"
    on:
      branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: "$AWS_SERECT_KEY"
